CREATE TABLE ITEM (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50)   NOT NULL,
    DESCRIPTION VARCHAR(500)    NOT NULL,
    PRICE   BIGINT  NOT NULL,
    IMAGE   VARCHAR(500)   NOT NULL
);