CREATE TABLE ITEM (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50)   NOT NULL,
    DESCRIPTION VARCHAR(500)    NOT NULL,
    PRICE   BIGINT  NOT NULL,
    IMAGE   VARCHAR(500)   NOT NULL
);

CREATE TABLE CUSTOMER (
      ID BIGINT AUTO_INCREMENT PRIMARY KEY,
      FIRSTNAME VARCHAR(50)   NOT NULL,
      LASTNAME VARCHAR(50)   NOT NULL,
      EMAIL VARCHAR(50)   NOT NULL,
      ADDRESS VARCHAR(250)   NOT NULL,
      COUNTRY VARCHAR(50)   NOT NULL,
      ZIPCODE VARCHAR(50)   NOT NULL,
      );